apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: web-namespace
spec:
  selector:
    type: frontend
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort