apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webapp
  namespace: web-namespace
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name : webapp-container
          image: nginx